schema_version: "1.0"

producers:
  - name: composite-monorepo
    build_system: bazel
    repository: https://github.com/pravasna30-dev/bazel-monorepo.git
    ref: main
    path: ../bazel-monorepo
    targets:
      - "//low-level-1:LowLevelOne"
    imports:
      - class: com.acme.arc.dep.test.LowOneMain
        call: LowOneMain.say()

  - name: dep-library
    build_system: source
    repository: https://github.com/pravasna30-dev/dep-library.git
    ref: main
    path: ../dep-library
    source_root: src/main/java
    package_name: library
    target: "//library:library"
    imports:
      - class: com.example.library.UserService
        call: "System.out.println(\"All users: \" + new UserService().findAll())"
