schema_version: "1.0"

producers:
  - name: composite-monorepo
    repository: https://github.com/pravasna30-dev/bazel-monorepo.git
    ref: main
    path: ../bazel-monorepo
    targets:
      - "//low-level-1:LowLevelOne"
    imports:
      - class: com.acme.arc.dep.test.LowOneMain
        call: LowOneMain.say()
